# logback
logging:
  config: classpath:logback.xml
  path: E:\self\logs\huaxing-site\gateway


spring:
  cloud:
    gateway:
      routes:
        - id:  blog-provider-route
          # lb代表从注册中心获取服务
          uri: ${hb.server.system}
          predicates:
          - Path=/sys/**
          filters:
          - StripPrefix=1

  #security 配置
  security:
    user:
      name: admin
      password: 123456

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:1316/eureka/







