# logback
logging:
  config: classpath:logback.xml
  path: E:\self\logs\huaxing-site\system
  level:
    druid:
      sql:
        Statement: DEBUG

#数据源
spring:
  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      password: My_site3610379@2019
      url: jdbc:mysql://39.100.233.12:3306/hb_system?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowMultiQueries=true
      username: root
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,config
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录 config.decrypt.key=${publicKey}
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      filter:
        wall:
          enabled: true
          config:
            # 开启批量提交
            multi-statement-allow: true
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-log-enabled: false
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true
          result-set-log-enabled: false

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    timeout: 3000


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: system-server
  client:
    service-url:
      defaultZone: http://localhost:1316/eureka/

