server:
  port: 1316                    # 指定该Eureka实例的端口

# logback
logging:
  config: classpath:logback.xml
  path: E:\self\logs\huaxing-site\eureka



eureka:
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 清理服务器
    eviction-interval-timer-in-ms: 5000
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false





